### PR TITLE
Fix: solscans links and add new link to solana.fm

### LINKED ISSUE #98: [Task]: fix broken link to view candy machine in solscan
**Describe the bug**
The url to view CM in solscan seems broken. 

**To Reproduce**
Click on "view on solscan"
image

**Expected behavior**
The url brings you to the cm account in solscan.

**Screenshots**
But it brings you here
image

### PR DESCRIPTION
**Pull request by cpl121**
Fixes #98

- Fix broken solscan url adding ` / ` at the end

## Changes

  - Add new link to solana.fm to view accounts and transactions
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

### CODE REVIEW

File: components/Modal.tsx [hunk 1]
```diff
@@ -50,36 +50,61 @@ const Modal: FC<{
...
-                                rel='noopener noreferrer'
-                            >
-                                View in Solscan
-                            </a>
+                            <div className='mt-5'>
+                                <a
+                                    className='text-blue-700 hover:underline my-3 mt-4 mr-2'
+                                    href={`https://solscan.io/account/${account}${
+                                        connection.rpcEndpoint.includes('devnet') ? '?cluster=devnet' : ''
+                                    }/`}
```
Comment (agus-xyz) [inline components/Modal.tsx:58]: adding the `/` actually does not fix the issue, but makes it a bit worst since the shown address is in the wrong cluster.

File: components/Modal.tsx [hunk 2]
```diff
@@ -50,36 +50,61 @@ const Modal: FC<{
...
                                 {!isLoading && tx && !error && (
                                     <>
                                         <span className='flex flex-col justify-center items-center mt-6'>
                                             Successfully closed account - Reedemed {tx.balanceChange.toFixed(4)} SOL
                                             <a
-                                                className='text-blue-700 hover:underline my-3'
+                                                className='text-blue-700 hover:underline my-1'
                                                 href={`https://solscan.io/tx/${tx.txid}${
                                                     connection.rpcEndpoint.includes('devnet') ? '?cluster=devnet' : ''
+                                                }/`}
```
Comment (agus-xyz) [inline components/Modal.tsx:91]: same here

File: pages/view-candy-machine/[id].tsx [hunk 3]
```diff
@@ -43,16 +43,29 @@ const ViewCandyMachine: NextPage = () => {
...
-                            rel='noopener noreferrer'
-                        >
-                            View in Solscan
-                        </a>
+                        <div className='mt-5'>
+                            <a
+                                className='text-blue-700 mt-4 mr-2'
+                                href={`https://solscan.io/account/${candyMachineAccount}${
+                                    connection.rpcEndpoint.includes('devnet') ? '?cluster=devnet' : ''
+                                }/`}
```
Comment (agus-xyz) [inline pages/view-candy-machine/[id].tsx:51]: same here

File: pages/verify-candy-machine/[id].tsx [hunk 4]
```diff
@@ -25,16 +25,29 @@ const VerifyCandyMachine: NextPage = () => {
...
-                            rel='noopener noreferrer'
-                        >
-                            View in Solscan
-                        </a>
+                        <div className='mt-5'>
+                            <a
+                                className='text-[hsl(258,52%,56%)] mt-4 mr-2'
+                                href={`https://solscan.io/account/${candyMachineAccount}${
+                                    connection.rpcEndpoint.includes('devnet') ? '?cluster=devnet' : ''
+                                }/`}
```
Comment (agus-xyz) [inline pages/verify-candy-machine/[id].tsx:33]: same here

File: pages/[id].tsx [hunk 5]
```diff
@@ -88,14 +88,29 @@ const CandyMachine: NextPage = () => {
...
+                            target='_blank'
+                            rel='noopener noreferrer'
+                        >
+                            View in Solscan
+                        </a>
+                        -
+                        <a
+                            className='text-[hsl(258,52%,56%)] mt-4 ml-2'
+                            href={`https://solana.fm/address/${candyMachineAccount}${
+                                connection.rpcEndpoint.includes('devnet') ? '?cluster=devnet-solana' : ''
```
Comment (aspnxdd) [inline pages/[id].tsx:106]: Since we use this in many places, we can extract to a util function `useExplorer` (or another name)
that receives the account/transaction/token that we need to show, and the connection from useConnection,
function returns the full url with or without the `?cluster=devnet`

**Review by aspnxdd — CHANGES_REQUESTED** [review]

**Comment by agus-xyz** [comment]
@cpl121 after the last changes, the design seems a bit broken
image
image

**Comment by begonaalvarezd** [comment]
> @cpl121 after the last changes, the layout I think broke a bit image image

This is known, is because primer css was added to the project. The design will be fixed little by little

**Comment by agus-xyz** [comment]
yes sorry for that, I did not know that was the state in dev
