### PR TITLE
Fix: open create cm and error mint button

### LINKED ISSUE #152: [Fix]: Error to mint button and redirect to create cm
**Task description.**

- Error to mint 1 nft when captcha is enabled
- A popup should open when creating a cm, instead of redirecting to create-candy-machine, when  there is none

### PR DESCRIPTION
**Pull request by cpl121**
Fixes #152

## Changes

  - Fix link to create cm
  - Fix error in mint button
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

### CODE REVIEW

File: pages/index.tsx [hunk 1]
```diff
@@ -67,11 +68,21 @@ const ManageCandyMachines: NextPage = () => {
                         </Button>
                     </div>
                 ) : !accounts?.length ? (
-                    <span className='mt-5'>
+                    <span className='mt-5 d-flex flex-row flex-items-center '>
```
Comment (evavirseda) [inline pages/index.tsx:71]: It is a good idea to make this change:
```suggestion
                    <div className='mt-5 d-flex flex-column flex-md-row flex-items-start flex-md-items-center '>
                        <div className='mr-2'>You have no candy machine accounts.</div>
                        <Button
                            className='color-bg-transparent text-semibold'
                            variant='invisible'
                            onClick={() => setIsOpen(true)}
                            sx={{ textTransform: 'capitalize', padding: '0' }}
                        >
                            Create one?
                        </Button>
                        {isOpen && (
                            <Popup onClose={() => setIsOpen(false)} title='Create Candy Machine' size='large'>
                                <CreateCandyMachine />
                            </Popup>
                        )}
                    </div>
```

**Review by evavirseda — CHANGES_REQUESTED** [review]
Nice :rocket: just one suggestion

**Review by evavirseda — APPROVED** [review]
:fire:
