### PR TITLE
Fix/network switch bug

### LINKED ISSUE #158: [Task]: Candy machine not found error
**Task description.**
When first loading into a Candy Machine that is not in the correct network it won't show any error.

**Requirements.**
Display the error message if the candy machine doesn't exists in the selected network. This has to work even when changing networks.

### PR DESCRIPTION
**Pull request by aspnxdd**
Fixes #158 

## Changes

  - Fix bug with loading cm on wrong network.
  
### Checks

* [x] Have you catchup your branch with the latest state in base?
* [x] Have you lint your code locally prior to submission?
* [x] Have you reviewed your proposed changes and removed debris?
* [x] Have you successfully ran due tests with your changes?

### CODE REVIEW

File: pages/[id].tsx [hunk 1]
```diff
@@ -118,18 +119,18 @@ const CandyMachine: NextPage = () => {
...
+        setError('')
+        setIsLoading(false)
         ;(async function () {
-            setError('')
-            fetchCandyMachine().then(setCandyMachineConfig)
-            refreshCandyMachineState()
-            await getNfts()
+            const data = await fetchCandyMachine()
+            setCandyMachineConfig(data)
+            // I comment this for now, takes lots of time and cant see anything
```
Comment (cpl121) [inline pages/[id].tsx:127]: Is the comment still needed?

File: components/NetworkSelector.tsx [hunk 2]
```diff
@@ -2,23 +2,45 @@ import { FC, useEffect, useRef } from 'react'
...
+const RPC_API_MAINNET = process.env.NEXT_PUBLIC_RPC_API_MAINNET as string
+
+function getUrl(network: Network): string {
+    switch (network) {
+        case 'Devnet':
+            return RPC_API_DEVNET
+        case 'Mainnet':
+            return RPC_API_MAINNET
+        default:
+            throw new Error(`Unknown network: ${network}`)
```
Comment (cpl121) [inline components/NetworkSelector.tsx:19]: I get this error when starting the app

Comment (evavirseda) [reply components/NetworkSelector.tsx:19]: me too
```suggestion
           throw new Error(` ${network}`)
```

**Review by evavirseda — APPROVED** [review]
Looks like it works nice :rocket: just conflicts!!

File: pages/[id].tsx (hunk 1 above)
Comment (aspnxdd) [reply pages/[id].tsx:127]: Yes. Takes more than 1 min for me but thats not an issue. In my opinion, the isLoading state should be split between the cmConfig and another state for the nftPart. Because we could show the config while the NFTs load.

Comment (VmMad) [reply pages/[id].tsx:127]: > Yes. Takes more than 1 min for me but thats not an issue. In my opinion, the isLoading state should be split between the cmConfig and another state for the nftPart. Because we could show the config while the NFTs load.

I changed this in [#149](https://github.com/boxfish-studio/sugar-rush/pull/149)

Comment (aspnxdd) [reply pages/[id].tsx:127]: > > Yes. Takes more than 1 min for me but thats not an issue. In my opinion, the isLoading state should be split between the cmConfig and another state for the nftPart. Because we could show the config while the NFTs load.
> 
> I changed this in [#149](https://github.com/boxfish-studio/sugar-rush/pull/149)

Oh sorry buddy, ill uncomment it then!

**Review by cpl121 — APPROVED** [review]
Perfect!
